version: '2'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - FSTT_POSTGRES_URL=jdbc:postgresql://db:5432/postgres
      - FSTT_POSTGRES_USER=postgres
      - FSTT_POSTGRES_PASS=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    ports:
      - 8080:8080
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456